language: python

services:
  - docker

before_install:
  docker build --tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
  docker run --name python-app -p 5000:5000 ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}


script:
  - curl 0.0.0.0:5000
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
